insert into professions values ('1');
insert into professions values ('2');
insert into professions values ('3');
insert into professions values ('4');
insert into professions values ('5');
insert into professions values ('6');
insert into professions values ('7');
insert into professions values ('8');
insert into professions_translation(profession, lang, name) values (1, 'eng', 'Alchemy');
insert into professions_translation(profession, lang, name) values (2, 'eng', 'Gathering');
insert into professions_translation(profession, lang, name) values (3, 'eng', 'Jewelcrafting');
insert into professions_translation(profession, lang, name) values (4, 'eng', 'Blacksmithing');
insert into professions_translation(profession, lang, name) values (5, 'eng', 'Artificing');
insert into professions_translation(profession, lang, name) values (6, 'eng', 'Armorsmithing');
insert into professions_translation(profession, lang, name) values (7, 'eng', 'Leatherworking');
insert into professions_translation(profession, lang, name) values (8, 'eng', 'Tailoring');
insert into professions_translation(profession, lang, name) values (1, 'fra', 'Alchimie');
insert into professions_translation(profession, lang, name) values (2, 'fra', 'Aprovisionnement');
insert into professions_translation(profession, lang, name) values (3, 'fra', 'Joallerie');
insert into professions_translation(profession, lang, name) values (4, 'fra', 'Forge');
insert into professions_translation(profession, lang, name) values (5, 'fra', 'Orfèvrerie');
insert into professions_translation(profession, lang, name) values (6, 'fra', 'Armurerie');
insert into professions_translation(profession, lang, name) values (7, 'fra', 'Maroquinerie');
insert into professions_translation(profession, lang, name) values (8, 'fra', 'Couture');
